export default endPoint = {
  registrationUser: '/api/registration/user',
  getListProvinsi: '/api/provinsi/list-of-provinsi',
  login: '/api/auth/login',
  getListKabupaten: '/api/kabupaten/list-of-kabupaten',
  getListKecamatan: '/api/kecamatan/list-of-kecamatan',
  getDetailCustomer: '/api/customer/get-detail-customer',
  getDetailVendor: '/api/vendor/get-detail-vendor',
  updateVendor: '/api/vendor/update',
  updateCustomer: '/api/customer/update',
  logout: '/api/auth/logout',
  getListKategory: '/api/kategory/get-list-kategory',
  getListVendorByKategory: '/api/kategory/get-list-vendor',
  getListProductByVendor: '/api/product/list-of-product',
  uploadProduct: '/api/product/upload',
  changePassword: '/api/registration/change-password',
  getProductVendor: '/api/product/get-product-vendor',
  createProduct: '/api/product/create-product',
  myListOfProduct: '/api/product/my-list-of-product',
  listOfProductExclude: '/api/product/list-of-product-exclude',
  getListProductByKategory: '/api/product/get-list-product-by-kategory',
  getProductDetail: '/api/product/get-product-detail',
  updateProduct: '/api/product/update-product',
  getListVendor: '/api/vendor/list-of-vendor',
};
